/* eslint-disable max-lines */
export const dataDashboard = [
  {
    projectId: '1',
    projectName: 'ARIA VŨNG TÀU',
    teamId: '1',
    teamName: 'ANT',
    products: 5,
    booking: 0,
    paid: 0,
    deposit: 0,
    cancel: 0,
    createdSale: '',
  },
  {
    projectId: '1',
    projectName: 'ARIA VŨNG TÀU',
    teamId: '2',
    teamName: 'DKRD',
    products: 1,
    booking: 1,
    paid: 1,
    deposit: 1,
    cancel: 1,
    createdSale: '',
  },
  {
    projectId: '1',
    projectName: 'ARIA VŨNG TÀU',
    teamId: '3',
    teamName: 'DKRE',
    products: 2,
    booking: 2,
    paid: 2,
    deposit: 2,
    cancel: 2,
    createdSale: '',
  },
  {
    projectId: '1',
    projectName: 'ARIA VŨNG TÀU',
    teamId: '4',
    teamName: 'DKRP',
    products: 3,
    booking: 3,
    paid: 3,
    deposit: 3,
    cancel: 3,
    createdSale: '',
  },
  {
    projectId: '1',
    projectName: 'ARIA VŨNG TÀU',
    teamId: '5',
    teamName: 'DKRT',
    products: 4,
    booking: 4,
    paid: 4,
    deposit: 4,
    cancel: 4,
    createdSale: '',
  },
  {
    projectId: '2',
    projectName: 'BIÊT THỰ BLUE SAPPHIRE',
    teamId: '1',
    teamName: 'ANT',
    products: 55,
    booking: 0,
    paid: 0,
    deposit: 0,
    cancel: 0,
    createdSale: '',
  },
  {
    projectId: '2',
    projectName: 'BIÊT THỰ BLUE SAPPHIRE',
    teamId: '2',
    teamName: 'DKRD',
    products: 100,
    booking: 10,
    paid: 0,
    deposit: 10,
    cancel: 0,
    createdSale: '',
  },
  {
    projectId: '2',
    projectName: 'BIÊT THỰ BLUE SAPPHIRE',
    teamId: '3',
    teamName: 'DKRE',
    products: 0,
    booking: 0,
    paid: 0,
    deposit: 0,
    cancel: 0,
    createdSale: '',
  },
  {
    projectId: '2',
    projectName: 'BIÊT THỰ BLUE SAPPHIRE',
    teamId: '4',
    teamName: 'DKRP',
    products: 0,
    booking: 0,
    paid: 0,
    deposit: 0,
    cancel: 0,
    createdSale: '',
  },
  {
    projectId: '2',
    projectName: 'BIÊT THỰ BLUE SAPPHIRE',
    teamId: '5',
    teamName: 'DKRT',
    products: 0,
    booking: 0,
    paid: 0,
    deposit: 0,
    cancel: 0,
    createdSale: '',
  },
  {
    projectId: '3',
    projectName: 'THE ROYAL ĐÀ NẴNG',
    teamId: '1',
    teamName: 'ANT',
    products: 45,
    booking: 0,
    paid: 0,
    deposit: 0,
    cancel: 0,
    createdSale: '',
  },
  {
    projectId: '3',
    projectName: 'THE ROYAL ĐÀ NẴNG',
    teamId: '2',
    teamName: 'DKRD',
    products: 0,
    booking: 0,
    paid: 0,
    deposit: 0,
    cancel: 0,
    createdSale: '',
  },
  {
    projectId: '3',
    projectName: 'THE ROYAL ĐÀ NẴNG',
    teamId: '3',
    teamName: 'DKRE',
    products: 0,
    booking: 0,
    paid: 0,
    deposit: 0,
    cancel: 0,
    createdSale: '',
  },
  {
    projectId: '3',
    projectName: 'THE ROYAL ĐÀ NẴNG',
    teamId: '4',
    teamName: 'DKRP',
    products: 0,
    booking: 0,
    paid: 0,
    deposit: 0,
    cancel: 0,
    createdSale: '',
  },
  {
    projectId: '3',
    projectName: 'THE ROYAL ĐÀ NẴNG',
    teamId: '5',
    teamName: 'DKRT',
    products: 0,
    booking: 0,
    paid: 0,
    deposit: 0,
    cancel: 0,
    createdSale: '',
  },
  {
    projectId: '4',
    projectName: 'HAPPY HOME CM',
    teamId: '1',
    teamName: 'ANT',
    products: 155,
    booking: 0,
    paid: 0,
    deposit: 0,
    cancel: 0,
    createdSale: '',
  },
  {
    projectId: '4',
    projectName: 'HAPPY HOME CM',
    teamId: '2',
    teamName: 'DKRD',
    products: 0,
    booking: 0,
    paid: 0,
    deposit: 0,
    cancel: 0,
    createdSale: '',
  },
  {
    projectId: '4',
    projectName: 'HAPPY HOME CM',
    teamId: '3',
    teamName: 'DKRE',
    products: 0,
    booking: 0,
    paid: 0,
    deposit: 0,
    cancel: 0,
    createdSale: '',
  },
  {
    projectId: '4',
    projectName: 'HAPPY HOME CM',
    teamId: '4',
    teamName: 'DKRP',
    products: 0,
    booking: 0,
    paid: 0,
    deposit: 0,
    cancel: 0,
    createdSale: '',
  },
  {
    projectId: '4',
    projectName: 'HAPPY HOME CM',
    teamId: '5',
    teamName: 'DKRT',
    products: 0,
    booking: 0,
    paid: 0,
    deposit: 0,
    cancel: 0,
    createdSale: '',
  },
  {
    projectId: '5',
    projectName: 'BARIA CITY',
    teamId: '1',
    teamName: 'ANT',
    products: 15,
    booking: 0,
    paid: 0,
    deposit: 0,
    cancel: 0,
    createdSale: '',
  },
  {
    projectId: '5',
    projectName: 'BARIA CITY',
    teamId: '2',
    teamName: 'DKRD',
    products: 0,
    booking: 0,
    paid: 0,
    deposit: 0,
    cancel: 0,
    createdSale: '',
  },
  {
    projectId: '5',
    projectName: 'BARIA CITY',
    teamId: '3',
    teamName: 'DKRE',
    products: 0,
    booking: 0,
    paid: 0,
    deposit: 0,
    cancel: 0,
    createdSale: '',
  },
  {
    projectId: '5',
    projectName: 'BARIA CITY',
    teamId: '4',
    teamName: 'DKRP',
    products: 0,
    booking: 0,
    paid: 0,
    deposit: 0,
    cancel: 0,
    createdSale: '',
  },
  {
    projectId: '5',
    projectName: 'BARIA CITY',
    teamId: '5',
    teamName: 'DKRT',
    products: 0,
    booking: 0,
    paid: 0,
    deposit: 0,
    cancel: 0,
    createdSale: '',
  },
];

export const dataByProject = [
  {
    teamId: '1',
    teamName: 'ANT',
    products: 50,
    booking: 65,
    paid: 18,
    deposit: 23,
    cancel: 5,
    createdSale: '',
  },
  {
    teamId: '2',
    teamName: 'DKRD',
    products: 120,
    booking: 98,
    paid: 88,
    deposit: 77,
    cancel: 55,
    createdSale: '',
  },
  {
    teamId: '3',
    teamName: 'DKRE',
    products: 120,
    booking: 98,
    paid: 88,
    deposit: 77,
    cancel: 55,
    createdSale: '',
  },
  {
    teamId: '4',
    teamName: 'DKRP',
    products: 120,
    booking: 98,
    paid: 88,
    deposit: 77,
    cancel: 55,
    createdSale: '',
  },
  {
    teamId: '5',
    teamName: 'DKRT',
    products: 120,
    booking: 98,
    paid: 23,
    deposit: 98,
    cancel: 55,
    createdSale: '',
  },
];

export const dataByTeam = [
  {
    projectId: '1',
    projectName: 'ARIA VŨNG TÀU',
    products: 50,
    booking: 65,
    paid: 18,
    deposit: 23,
    cancel: 5,
    createdSale: '',
  },
  {
    projectId: '2',
    projectName: 'BIÊT THỰ BLUE SAPPHIRE',
    products: 120,
    booking: 98,
    paid: 88,
    deposit: 77,
    cancel: 55,
    createdSale: '',
  },
  {
    projectId: '3',
    projectName: 'THE ROYAL ĐÀ NẴNG',
    products: 120,
    booking: 98,
    paid: 88,
    deposit: 77,
    cancel: 55,
    createdSale: '',
  },
  {
    projectId: '4',
    projectName: 'HAPPY HOME CM',
    products: 120,
    booking: 98,
    paid: 88,
    deposit: 77,
    cancel: 55,
    createdSale: '',
  },
  {
    projectId: '5',
    projectName: 'BARIA CITY',
    products: 120,
    booking: 98,
    paid: 23,
    deposit: 98,
    cancel: 55,
    createdSale: '',
  },
];
