export const VALIDATION = {
  MAIL_REQUIRED: 'Vui lòng nhập email',
  MAIL_PATTERN: 'Email không hợp lệ',
  PASSWORD_REQUIRED: 'Vui lòng nhập mật khẩu',
  PASSWORD_MIN: 'Mật khẩu tối thiểu 6 ký tự',
};

// OLD
export const TASK_ACTIONS = {
  CREATE: 'CREATE',
  VIEW: 'VIEW',
  BACK: 'BACK',
  CLONE: 'CLONE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  ADJUST: 'ADJUST',
  COMPLETE: 'COMPLETE',
  COPY: 'COPY',
  RESET: 'RESET',
  CANCEL: 'CANCEL',
  UNLOCK: 'UNLOCK',
  DELETE_SELECTED: 'DELETE_SELECTED',
  DELETE_ALL: 'DELETE_ALL',
  SLIDE_TOGGLE_CHANGE: 'SLIDE_TOGGLE_CHANGE',
};

export const BOOKING_STATUS = {
  NEW: 'New',
  NEW_TITLE: 'Mới',
  CANCEL: 'CancelTrans',
  CANCEL_TITLE: 'Hủy',
};

export const BOOKING_TYPE = {
  BOOKING: 'Booking',
  SOLD: 'Sold',
};

export const TRANSACTION_TYPE = {
  UPDATE: 'Update',
  ADJUSTED: 'Adjusted',
};

export const FINANCES_UPDATE_TYPE = {
  UPDATE_INFO: 'UpdateInfo',
  UPDATE_PLAN: 'UpdatePlan',
};

export const FINANCES_PLAN_ACTIVITY_CODE_TYPE = {
  FINANCIAL: 'Financial',
  OTHER: 'Other',
  PROJECT: 'Project',
  OPERATION: 'Operation',
};

export const TABLE_FILTER_TYPE = {
  DATETIME_RANGE: 'DATETIME_RANGE',
  MONTH_RANGE: 'MONTH_RANGE',
  SELECT_YEAR: 'SELECT_YEAR',
  SELECT_MONTH: 'SELECT_MONTH',
  SELECTBOX: 'SELECTBOX',
  CHECKBOX: 'CHECKBOX',
};

export const IMPORT_EXPORT = {
  PRODUCT_OVERVIEW: {
    EXPORT_TEMPLATE: 'EXPORT_TEMPLATE',
    EXPORT_LIST: 'EXPORT_LIST',
    EXPORT_LIST_ADJUSTED: 'EXPORT_LIST_ADJUSTED',
    IMPORT_CREATE: 'IMPORT_CREATE',
    IMPORT_UPDATE: 'IMPORT_UPDATE',
  },
  SALES_PLAN: {
    EXPORT_TEMPLATE: 'EXPORT_TEMPLATE',
    EXPORT_LIST: 'EXPORT_LIST',
    EXPORT_LIST_ADJUSTED: 'EXPORT_LIST_ADJUSTED',
    IMPORT_SALES_PLAN: 'IMPORT_SALES_PLAN',
    IMPORT_ADJUSTED: 'IMPORT_ADJUSTED',
    IMPORT_UPDATE_SALES_PLAN: 'IMPORT_UPDATE_SALES_PLAN',
  },
  MAKE_SALES: {
    EXPORT_TEMPLATE: 'EXPORT_TEMPLATE',
    EXPORT_LIST: 'EXPORT_LIST',
    EXPORT_ADJUST: 'EXPORT_ADJUST',
    EXPORT_LIST_NEED_CANCEL: 'EXPORT_LIST_NEED_CANCEL',
    IMPORT_NEW: 'IMPORT_NEW',
    IMPORT_CANCEL: 'IMPORT_CANCEL',
    IMPORT_UPDATE: 'IMPORT_UPDATE',
  },
  FINANCES_PLAN: {
    EXPORT_TEMPLATE: 'EXPORT_TEMPLATE',
    EXPORT_LIST: 'EXPORT_LIST',
    EXPORT_LIST_ADJUSTED: 'EXPORT_LIST_ADJUSTED',
    IMPORT_FINANCES_PLAN: 'IMPORT_FINANCES_PLAN',
    IMPORT_ADJUSTED: 'IMPORT_ADJUSTED',
  },
  IMPLEMENT_FINANCES: {
    EXPORT_TEMPLATE: 'EXPORT_TEMPLATE',
    EXPORT_LIST: 'EXPORT_LIST',
    EXPORT_UPDATE: 'EXPORT_UPDATE',
    IMPORT_LIST: 'IMPORT_LIST',
    IMPORT_UPDATE: 'IMPORT_UPDATE',
  },
};

export const ACTION_CRUD = {
  DELETE: 'DELETE',
  UPDATE: 'UPDATE',
  SAVE_CONTINUE: 'SAVE_CONTINUE',
  SAVE: 'SAVE',
  REFILL: 'REFILL',
  CANCEL: 'CANCEL',
};

export const PAGE_STATUS = {
  CREATE: 'CREATE',
  READ: 'READ',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
};

export const CREATE_TEXT = 'create';
